#!/usr/bin/env bash
set -Eeu -o pipefail
CommandNotFound() { for cmd in "${@:?"CommandNotFound: \$@ as commands is required"}"; do if ! command -v "${cmd:?}" >/dev/null; then echo "${cmd:?}"; return 0; fi; done; return 1; }
if CommandNotFound jq; then
  cat
else
  cat | jq -Rr '. as $line | try fromjson catch $line'
fi
